stages:
  - test
  - build
  - js_build
  - deploy

sast:
  stage: test
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SAST_VERSION=${SP_VERSION:-$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')}
    - |
      docker run \
        --env SAST_ANALYZER_IMAGES \
        --env SAST_ANALYZER_IMAGE_PREFIX \
        --env SAST_ANALYZER_IMAGE_TAG \
        --env SAST_DEFAULT_ANALYZERS \
        --env SAST_BRAKEMAN_LEVEL \
        --env SAST_GOSEC_LEVEL \
        --env SAST_FLAWFINDER_LEVEL \
        --env SAST_DOCKER_CLIENT_NEGOTIATION_TIMEOUT \
        --env SAST_PULL_ANALYZER_IMAGE_TIMEOUT \
        --env SAST_RUN_ANALYZER_TIMEOUT \
        --volume "$PWD:/code" \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        "registry.gitlab.com/gitlab-org/security-products/sast:$SAST_VERSION" /app/bin/run /code
  dependencies: []
  artifacts:
    reports:
      sast: gl-sast-report.json

build:
  stage: build
  image: composer
  script:
    - composer install -on --ignore-platform-reqs --no-progress --no-dev
  cache:
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
    when: on_success
    expire_in: 1h
  only:
    - develop

js_build:
  stage: js_build
  image: node:8.11.2
  script:
    - npm install apidoc -g
    - apidoc -i docs/ -o public/apidoc/
  artifacts:
    paths:
      - public/apidoc/
    when: on_success
    expire_in: 1h
  only:
    - develop

deploy:
  stage: deploy
  image: dinofizz/rsync-ssh
  script:

    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

    - sed -i -e "s/%server_name%/${SSH_SERVER_HOST}/g" ./docker/nginx.conf
    - sed -i -e "s/%server_name%/${SSH_SERVER_HOST}/g" ./docker/nginx_ssl.conf

    - mkdir ./ssl
    - echo "$SSL_CERTIFICATE" > ./ssl/certificate.crt
    - echo "$SSL_PRIVATE_KEY" > ./ssl/private.key

    - cp docker-compose.yml.develop docker-compose.yml
    - rm docker-compose.yml.*

    - echo -e "$ENV" > ./.env

    - rm -rf ./.git
    - rm -rf ./tests

    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_HOST "mkdir -p /var/www/wish"
    - rsync -az --exclude-from=.gitlab-ci-exclude --no-perms --no-owner --no-group --delete-during -e "ssh -o StrictHostKeyChecking=no" . $SSH_USER@$SSH_SERVER_HOST:/var/www/wish
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_SERVER_HOST "cd /var/www/wish && docker-compose up -d --force-recreate --remove-orphans && docker exec wish_php /bin/bash ./init_dev.sh"
  only:
    - develop
