version: '3'

services:
  db:
    image: "mysql:5.7"
    ports:
      - "3333:3306"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: pitchingon
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'
  web:
    build: .
    ports:
      - "8888:80"
      - "443:443"
    links:
      - db:database_host
    volumes:
      - ./:/var/www/html
      - ./ssl:/var/www/ssl
    environment:
      _ENV: development
      _XDEBUG_REMOTE_HOST: 192.168.0.103
      _XDEBUG_REMOTE_PORT: 9000
      SERVER_NAME: stage.pickldating.co.uk
      SSL: "on"
    depends_on:
      - db
    restart: unless-stopped
volumes:
  db_data:
