<?php

namespace Tests;

use App\Modules\Categories\Models\Category;
use App\Modules\Products\Models\Product;
use App\Modules\Users\Customer\Models\Customer;
use App\Modules\Users\Merchant\Models\Merchant;
use App\Modules\Users\Merchant\Models\Store;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Collection;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use RefreshDatabase;
   // use DatabaseTransactions;

    /**
     * @var Customer
     */
    protected $authCustomer;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->authCustomer = factory(Customer::class)->create();
        $this->authCustomer->deliveryInformation()->create([
            'country' => 'en',
            'city' => 'City',
            'apartment' => 'apt',
            'street' => 'Street',
            'state' => 'State',
            'zip' => 'zip',
            'notes' => 'Notes',
            'phone' => '88005553535',
        ]);
    }

    protected function apiAuthToken()
    {
        if (null === $this->authCustomer) {
            return null;
        }

        return auth()->guard('customer')->login($this->authCustomer);
    }


    protected function requestAuthorized(string $method, string $url, array $data = [], $files = [], array $headers = [], string $token = null)
    {
        if (null === $token) {
            $token = $this->apiAuthToken();
        }
        $headers = array_merge(['Authorization' => "Bearer {$token}"], $headers);
        $server = $this->transformHeadersToServerVars($headers);
        dd($data);
        return $this->call($method, $url, $data, [], $files, $server);
    }

    protected function jsonAuthorized(string $method, string $url, array $data = [], array $headers = [], string $token = null)
    {
        $files = $this->extractFilesFromDataArray($data);
        $content = json_encode($data);

        if (null === $token) {
            $token = $this->apiAuthToken();
        }

        $headers = array_merge([
            'CONTENT_LENGTH' => mb_strlen($content, '8bit'),
            'CONTENT_TYPE' => 'application/json',
            'Accept' => 'application/json',
            'Authorization' => "Bearer {$token}"
        ], $headers);
        return $this->call(
            $method, $url, [], [], $files, $this->transformHeadersToServerVars($headers), $content
        );
    }

    /**
     * @param array $attr
     * @param int $count
     * @return Collection
     */
    public function mockProduct(array $attr = [], int $count = 1) : Collection
    {

        $merchant = factory(Merchant::class)->create();
        $store = factory(Store::class)->create([
            'merchant_id' => $merchant->id,
        ]);
        if (array_key_exists('category_id', $attr)) {
            $category = factory(Category::class)->create(['id' => $attr['category_id']]);
        } else {
            $category = factory(Category::class)->create();
        }

        $attr = array_merge($attr, [
            'store_id' => $store->id,
            'category_id' => $category->id,
        ]);
        return factory(Product::class, $count)->create($attr);
    }
}
